# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f610dc2b8a3017b380e42acfea487896a2f27af90df40c49158237565253fc5eafca0f39c55a10824af9b8664e6183ada7973650fdd0268bb0c53afa6471c78

test:
  secret_key_base: 0f5696d96238abaeeec7d3375d92f0f68b167eaf52324f0a8614970402c907db23f08ab231b55d8201e13dd66cca8c6c5bb09000ae4b27409b3feb5a2d7cc638

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
